import { createSlice } from "@reduxjs/toolkit";
import Cookies from "js-cookie";

const initialState = {
  token: Cookies.get('Token') || null, // Initialize the token from Cookies
  isAuthenticated: !!Cookies.get('Token'), // Check if a token exists in Cookies for initial isAuthenticated state
};

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    // Action for setting the user token when they log in.
    login: (state, action) => {
      state.token = action.payload;
      state.isAuthenticated = true;
      Cookies.set('Token', action.payload, { expires: 7 }); // Save the token to Cookies
    },
    // Action for logging the user out.
    logout: (state) => {
      state.token = null;
      state.isAuthenticated = false;
      Cookies.remove('Token'); // Remove the token from Cookies
    },
  },
});

// Export the action creators generated by createSlice.
export const { login, logout } = authSlice.actions;

// Export the reducer for the authentication slice.
export default authSlice.reducer;
